#!/bin/bash

# MEDIAN BLOG API - COMMAND REFERENCE
# Copy-paste salah satu perintah di bawah ke terminal Anda


echo ""
echo "╔═══════════════════════════════════════════════════════════╗"
echo "║  MEDIAN BLOG API - COMMAND REFERENCE                      ║"
echo "╚═══════════════════════════════════════════════════════════╝"
echo ""
echo "PILIH SALAH SATU CARA UNTUK MEMULAI:"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "CARA 1: AUTO-SETUP (LINUX/MACOS) - TERMUDAH"
echo "─────────────────────────────────────────────"
echo ""
echo "cd /workspaces/nest-lab-crud && bash start.sh"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "CARA 2: MANUAL SETUP (SEMUA OS) - DETAIL"
echo "─────────────────────────────────────────"
echo ""
echo "# Step 1: Navigate to project"
echo "cd /workspaces/nest-lab-crud/median"
echo ""
echo "# Step 2: Install dependencies"
echo "npm install"
echo ""
echo "# Step 3: Start PostgreSQL"
echo "docker compose up -d"
echo ""
echo "# Step 4: Run migrations"
echo "npx prisma migrate deploy"
echo ""
echo "# Step 5: Seed database (optional but recommended)"
echo "npm run prisma:seed"
echo ""
echo "# Step 6: Start development server"
echo "npm run start:dev"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "SETELAH SERVER RUNNING:"
echo "─────────────────────"
echo ""
echo "📱 API: http://localhost:3000"
echo "📚 Swagger UI: http://localhost:3000/api"
echo "🗄️  Database: npx prisma studio"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "USEFUL COMMANDS:"
echo "──────────────"
echo ""
echo "# Start development server"
echo "npm run start:dev"
echo ""
echo "# View database in GUI"
echo "npx prisma studio"
echo ""
echo "# Create new migration"
echo "npx prisma migrate dev --name migration_name"
echo ""
echo "# Seed database"
echo "npm run prisma:seed"
echo ""
echo "# Reset database (⚠️ clears all data)"
echo "docker compose down -v && docker compose up -d"
echo "npx prisma migrate deploy"
echo "npm run prisma:seed"
echo ""
echo "# Check PostgreSQL status"
echo "docker compose ps"
echo ""
echo "# Stop all services"
echo "docker compose down"
echo ""
echo "# View database logs"
echo "docker compose logs -f postgres"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "TEST CREDENTIALS:"
echo "───────────────"
echo ""
echo "Email:    sabin@adams.com"
echo "Password: password-sabin"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "DOCUMENTATION FILES:"
echo "───────────────────"
echo ""
echo "00-BACA-DULU.txt         ← Quick reference (text)"
echo "INDEX.md                  ← File navigation"
echo "START.md                  ← Quick start guide"
echo "QUICK_START.md            ← Step-by-step setup (RECOMMENDED!)"
echo "SETUP_GUIDE.md            ← Troubleshooting & advanced"
echo "chapter-1/ hingga 4/      ← Tutorial files"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
